{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "K6 - RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(k6_http_reqs_total[1m]))",
     "legendFormat": "__auto"
    },
    { "expr": "rate(k6_http_reqs_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "__auto" },
    { "expr": "sum(http_requests_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency P95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, endpoint) (rate(http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vus",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "targets": [
    { "expr": "k6_vus", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Duration p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
   "targets": [
    { "expr": "k6_http_req_duration_p99", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Blocked p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "targets": [
    { "expr": "k6_http_req_blocked_p99", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Waiting p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "targets": [
    { "expr": "k6_http_req_waiting_p99", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Queue- Total Messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "targets": [
    { "expr": "rabbitmq_queue_messages", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Failed rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 15 },
   "targets": [
    { "expr": "sum(k6_http_req_failed_rate)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rabbitmq messages total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 15 },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_delivered_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue: Incoming",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 15 },
   "targets": [
    {
     "expr": "rate(rabbitmq_queue_messages_published_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue: Outgoing",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 15 },
   "targets": [
    {
     "expr": "rate(rabbitmq_queue_messages_delivered_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 21 },
   "targets": [
    { "expr": "rabbitmq_queue_messages_ready", "legendFormat": "__auto" }
   ]
  }
 ]
}