apiVersion: v1
kind: Service
metadata:
  name: order-postgres
  namespace: devops-dsols

spec:
  clusterIP: None

  selector:
    app: order-postgres

  ports:
    - port: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: order-postgres
  namespace: devops-dsols

spec:
  serviceName: order-postgres
  replicas: 1
  revisionHistoryLimit: 1

  selector:
    matchLabels:
      app: order-postgres

  template:
    metadata:
      labels:
        app: order-postgres

    spec:
      containers:
        - name: postgres
          image: postgres:15

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: order_db

            - name: POSTGRES_USER
              value: postgres

            - name: POSTGRES_PASSWORD
              value: password

          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"

            limits:
              cpu: "200m"
              memory: "256Mi"

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
    - metadata:
        name: postgres-storage

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: product-postgres
  namespace: devops-dsols

spec:
  clusterIP: None

  selector:
    app: product-postgres

  ports:
    - port: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: product-postgres
  namespace: devops-dsols

spec:
  serviceName: product-postgres
  replicas: 1
  revisionHistoryLimit: 1

  selector:
    matchLabels:
      app: product-postgres

  template:
    metadata:
      labels:
        app: product-postgres

    spec:
      containers:
        - name: postgres
          image: postgres:15

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: product_db

            - name: POSTGRES_USER
              value: postgres

            - name: POSTGRES_PASSWORD
              value: password

          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"

            limits:
              cpu: "200m"
              memory: "256Mi"

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
    - metadata:
        name: postgres-storage

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: user-postgres
  namespace: devops-dsols

spec:
  clusterIP: None

  selector:
    app: user-postgres

  ports:
    - port: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-postgres
  namespace: devops-dsols

spec:
  serviceName: user-postgres
  replicas: 1
  revisionHistoryLimit: 2

  selector:
    matchLabels:
      app: user-postgres

  template:
    metadata:
      labels:
        app: user-postgres

    spec:
      containers:
        - name: postgres
          image: postgres:15

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: user_db

            - name: POSTGRES_USER
              value: postgres

            - name: POSTGRES_PASSWORD
              value: password

          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"

            limits:
              cpu: "200m"
              memory: "256Mi"

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
    - metadata:
        name: postgres-storage

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 1Gi
