apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management
          command: ["bash", "-c", "rabbitmq-plugins enable --offline rabbitmq_prometheus && rabbitmq-server"]
          ports:
            - containerPort: 5672
            - containerPort: 15672
            - containerPort: 15692
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "ping"]
            initialDelaySeconds: 20
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 5
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: ui
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: metrics
      protocol: TCP
      port: 15692
      targetPort: 15692
