apiVersion: batch/v1
kind: Job

metadata:
  name: order-db-setup
  namespace: devops-dsols

spec:
  template:
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36

          command:
            [
              "sh",
              "-c",
              "until nc -z order-postgres 5432; do echo waiting for postgres; sleep 2; done;",
            ]

      containers:
        - name: postgres-setup

          image: devops-dsols-app:latest
          imagePullPolicy: IfNotPresent

          command: ["./app", "-type=init", "-component=order", "-config=/app/config/local.yml"]

          volumeMounts:
            - name: app-config-volume
              mountPath: /app/config/local.yml
              subPath: local.yml

      restartPolicy: OnFailure

      volumes:
        - name: app-config-volume
          configMap:
            name: app-config
